# Site settings
title: huang
email: sunhhjay@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  hhjay,一个来自天朝的人.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  hhjay

# Build settings
markdown: kramdown
